### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by JohnReedLOL** [sbt/sbt-pgp#98] opened 2017-02-26 16:22 UTC
```
johnreed@johnreed-Galago-UltraPro:~/Documents/Code/xiIntegrate/scala-trace-debug2$ gpg --list-keys
gpg: [don't know]: invalid packet (ctb=2d)
gpg: keydb_search_first failed: invalid packet
johnreed@johnreed-Galago-UltraPro:~/Documents/Code/xiIntegrate/scala-trace-debug2$ 
johnreed@johnreed-Galago-UltraPro:~/Documents/Code/xiIntegrate/scala-trace-debug2$ gpg --dearmor


^C
gpg: Interrupt caught ... exiting

johnreed@johnreed-Galago-UltraPro:~/Documents/Code/xiIntegrate/scala-trace-debug2$ sbt
[info] Loading project definition from /home/johnreed/Documents/Code/xiIntegrate/scala-trace-debug2/project
[info] Set current project to scala-trace-debug (in build file:/home/johnreed/Documents/Code/xiIntegrate/scala-trace-debug2/)
> pgp-cmd recv-key B8CF8F8E hkp://pool.sks-keyservers.net
INF: [console logger] dispatch: pool.sks-keyservers.net GET /pks/lookup?op=get&search=0xb8cf8f8e&options=mr HTTP/1.1
[info] Adding public key: PublicKeyRing(PublicKey(8640b24b8cf8f8e, John-Michael Reed <johnmichaelreedfas@gmail.com>, RSA@2048),PublicKey(cdbbe2cb27adb0c5, , RSA@2048))
> pgp-cmd send-key B8CF8F8E http://keyserver.ubuntu.com
Failed to run pgp-cmd: SendKey(B8CF8F8E,http://keyserver.ubuntu.com).   Please report this issue at http://github.com/sbt/sbt-pgp/issues
> 

johnreed@johnreed-Galago-UltraPro:~/Documents/Code/xiIntegrate/scala-trace-debug2$ 
johnreed@johnreed-Galago-UltraPro:~/Documents/Code/xiIntegrate/scala-trace-debug2$ sbt
[info] Loading project definition from /home/johnreed/Documents/Code/xiIntegrate/scala-trace-debug2/project
[info] Set current project to scala-trace-debug (in build file:/home/johnreed/Documents/Code/xiIntegrate/scala-trace-debug2/)
> pgp-cmd gen-key
Failed to run pgp-cmd: GeneratePgpKey().   Please report this issue at http://github.com/sbt/sbt-pgp/issues

```

**Comment by 0x7fh** [comment] 2017-10-08 18:52
I've had this “invalid packet” too. I think it is caused by the different format of the key rings. GPG 2.2 recently changed the format. This plugin uses BouncyCastle and it seems it has different opinions on the key ring format. I configured new key rings with the `pgpSecretRing` and `pgpPublicRing` settings and used them from now on. The “invalid packet” disappeared.

**Comment by jvican** [comment] 2017-10-26 12:51
Indeed, this is a duplicate of https://github.com/sbt/sbt-pgp/issues/72. Should be closed.

**Closed** 2017-11-03 02:16 UTC
