### ISSUE TITLE
Missleading error "gpg-agent is not available" 

### ISSUE THREAD

**Issue by ignasi35** [sbt/sbt-pgp#177] opened 2020-07-23 09:00 UTC
## steps

sbt-pgp version: 2.0.0
sbt version: 1.3.3

## problem

The error `[error] gpg: gpg-agent is not available in this session` is displayed even though the `gpg-agent` binary is installed and accessible for the particular user _and_ the artifacts seems to be properly signed.

## expectation

The error message should not be displayed when the signing process succeeds.

**Comment by eed3si9n** [comment] 2020-07-23 13:25
I think this is a duplicate of https://github.com/sbt/sbt-pgp/issues/174. sbt's log wrapper reports stderr output as error.

**Closed by eed3si9n** 2020-07-23 13:25 UTC

**Comment by asakaev** [comment] 2020-11-23 13:40
```
[error] gpg: gpg-agent is not available in this session
[error] gpg: gpg-agent is not available in this session
[error] gpg: gpg-agent is not available in this session
[error] gpg: gpg-agent is not available in this session
```

https://github.com/asakaev/leftpad/runs/1436631932?check_suite_focus=true#step:5:266

@eed3si9n Maybe there is a way to configure pgp to hide these reports?
