### ISSUE TITLE
docs wrong or autoimport not working in user global settings?

### ISSUE THREAD

**Issue by aryairani** [sbt/sbt-pgp#80] opened 2015-06-03 17:55 UTC
I have to use 
`com.typesafe.sbt.SbtPgp.autoImport.pgpPassphrase := ...` 
instead of 
`pgpPassphrase := ...`
in ~/.sbt/0.13/build.sbt.  The plugin is added in ~/.sbt/0.13/plugins/gpg.sbt
`> set pgpPassphrase := ...` works unqualified though.

Is that normal?

**Comment by Blaisorblade** [comment] 2015-07-21 12:45
#81 has more useful details.

**Comment by timcharper** [comment] 2016-01-17 23:17
Since #81 has more useful details, I recommend this issue be closed and marked as a duplicate of #81.

**Comment by timcharper** [comment] 2016-01-17 23:18
This isn't a bug with sbt-pgp, but a bug with sbt itself. (see sbt/sbt issue sbt/sbt#2120).

Basically, what's happening is AutoPlugin imports happens after the global config, and before the project config is loaded.

**Comment by eed3si9n** [comment] 2019-09-15 05:48
I am closing this due to inactivity, but if this is still relevant.

**Closed by eed3si9n** 2019-09-15 05:48 UTC
Labels: Bug
