### ISSUE TITLE
Imports and scope now required for global pgpPasspharase setting.

### ISSUE THREAD

**Issue by milessabin** [sbt/sbt-pgp#81] opened 2015-06-04 07:23 UTC
I recently moved from 0.8.1 to 1.0.0 and my `pgpPassphrase` setting in `~/.sbt/0.13/global.sbt`,

```scala
pgpPassphrase := Some("<redacted>".toArray)
```
stopped working. It was fixable by changing the `global.sbt` as follows,
```scala
import com.typesafe.sbt.pgp.PgpKeys.pgpPassphrase

pgpPassphrase in Global := Some("<redacted>".toArray)
```
The requirement for the additional import appears to be a side-effect of the move of the plugin from "com.typesafe" to "com.jsuereth". I don't see any obvious explanation for the scope change.

**Comment by fommil** [comment] 2015-06-15 19:21
:smile: thanks! That's the magic import I needed. I couldn't work it out even from reading the `sbt-pgp` source. The `AutoPlugin` stuff is just *way* too much magic for mere mortals like us.

**Comment by fommil** [comment] 2015-06-15 19:23
are you able to get this working with `sbt-release`? #74

**Comment by fommil** [comment] 2015-06-15 19:23
btw, I needed to do a

```
~/.sbt/0.13$ rm -rf target staging plugins/project plugins/target
```

**Comment by milessabin** [comment] 2015-06-15 19:23
It works with shapeless's multibranch release script.

**Comment by jsuereth** [comment] 2015-07-17 15:40
Thanks for the report @milessabin .  I'm still not 100% sure how this happened, will investigate.

**Comment by jsuereth** [comment] 2015-07-17 15:44
Duplicate of #81

**Closed by jsuereth** 2015-07-17 15:44 UTC

**Comment by Blaisorblade** [comment] 2015-07-21 12:49
I think this is an instance of sbt/sbt#2120. Between the working and non-working versions (https://github.com/sbt/sbt-pgp/compare/v0.8.1...v1.0.0), there's a commit transitioning to the new plugin architecture, just like in the other instance:
https://github.com/sbt/sbt-pgp/commit/4f1f80d23eaa413c178d1518a59e1f80cfecefdf

**Comment by jsuereth** [comment] 2015-07-22 14:55
@Blaisorblade Yeah. I think the issue is actually with eviction between global plugins and build-level plugins.  We may be succesfully evicted the JAR files before loading the project, but some of the plugin data may be stale.   I'll see if I can investigate and issue a solution to the eviction code.

Anyone have a reproducible test case?

**Comment by Blaisorblade** [comment] 2015-07-22 15:30
> Anyone have a reproducible test case?

I thought typesafehub/sbteclipse#295 was such a thing — see the transition from sbteclipse 2.5.0 to sbteclipse 4.0.0.

But wait: as I now realize, maybe you are saying that this is solved by:
```
~/.sbt/0.13$ rm -rf target staging plugins/project plugins/target
```
?
If so, my reproduction procedure might be incomplete. I guess loading sbteclipse 2.5.0 and switching to sbteclipse 4.0.0 would still do the trick, but I'd have to try.

**Comment by jsuereth** [comment] 2015-07-22 15:32
Yeah, this my be a combination of stale global cache detection AND exclusion issues.  I'll dive in with that assumptiona nd try to corrupt global plugin cache.

**Comment by Blaisorblade** [comment] 2015-07-23 00:12
Just to make things more fun, the sbteclipse error doesn't go away after removing all those directories — whether I just reload in the same SBT session, or I also exit and restart SBT.

**Comment by Blaisorblade** [comment] 2015-07-23 00:20
I also tried with sbt-pgp 1.0.0, but couldn't transition among releases.
However, sbt-pgp 1.0.0 just fails reliably without the needed imports before settings.

**Comment by timcharper** [comment] 2016-01-17 23:17
This isn't a bug with `sbt-pgp`, but a bug with `sbt` itself. (see sbt/sbt issue https://github.com/sbt/sbt/issues/2120).

Basically, what's happening is AutoPlugin imports happens after the global config, and before the project config is loaded.
